/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpectrumRouteImport } from './routes/spectrum'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as CapturesIndexRouteImport } from './routes/captures.index'
import { Route as CapturesCaptureIdRouteImport } from './routes/captures.$captureId'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsCalibrationRouteImport } from './routes/settings.calibration'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsLogsRouteImport } from './routes/settings.logs'
import { Route as SettingsMapRouteImport } from './routes/settings.map'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsSensorsRouteImport } from './routes/settings.sensors'
import { Route as SettingsTracksRouteImport } from './routes/settings.tracks'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksTrackIdRouteImport } from './routes/tracks.$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectrumRoute = SpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIndexRoute = CapturesIndexRouteImport.update({
  id: '/captures/',
  path: '/captures/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesCaptureIdRoute = CapturesCaptureIdRouteImport.update({
  id: '/captures/$captureId',
  path: '/captures/$captureId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCalibrationRoute = SettingsCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMapRoute = SettingsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSensorsRoute = SettingsSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTracksRoute = SettingsTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => SettingsRoute,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/docs': typeof DocsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/spectrum': typeof SpectrumRoute
  '/timeline': typeof TimelineRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/tracks': typeof SettingsTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/spectrum': typeof SpectrumRoute
  '/timeline': typeof TimelineRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/tracks': typeof SettingsTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures': typeof CapturesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/docs': typeof DocsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/spectrum': typeof SpectrumRoute
  '/timeline': typeof TimelineRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/tracks': typeof SettingsTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/config'
    | '/docs'
    | '/logs'
    | '/sensors'
    | '/settings'
    | '/spectrum'
    | '/timeline'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/calibration'
    | '/settings/data'
    | '/settings/general'
    | '/settings/logs'
    | '/settings/map'
    | '/settings/notifications'
    | '/settings/sensors'
    | '/settings/tracks'
    | '/tracks/$trackId'
    | '/captures/'
    | '/docs/'
    | '/settings/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/config'
    | '/logs'
    | '/sensors'
    | '/spectrum'
    | '/timeline'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/calibration'
    | '/settings/data'
    | '/settings/general'
    | '/settings/logs'
    | '/settings/map'
    | '/settings/notifications'
    | '/settings/sensors'
    | '/settings/tracks'
    | '/tracks/$trackId'
    | '/captures'
    | '/docs'
    | '/settings'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/config'
    | '/docs'
    | '/logs'
    | '/sensors'
    | '/settings'
    | '/spectrum'
    | '/timeline'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/calibration'
    | '/settings/data'
    | '/settings/general'
    | '/settings/logs'
    | '/settings/map'
    | '/settings/notifications'
    | '/settings/sensors'
    | '/settings/tracks'
    | '/tracks/$trackId'
    | '/captures/'
    | '/docs/'
    | '/settings/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConfigRoute: typeof ConfigRoute
  DocsRoute: typeof DocsRouteWithChildren
  LogsRoute: typeof LogsRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SpectrumRoute: typeof SpectrumRoute
  TimelineRoute: typeof TimelineRoute
  CapturesCaptureIdRoute: typeof CapturesCaptureIdRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  CapturesIndexRoute: typeof CapturesIndexRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectrum': {
      id: '/spectrum'
      path: '/spectrum'
      fullPath: '/spectrum'
      preLoaderRoute: typeof SpectrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/': {
      id: '/captures/'
      path: '/captures'
      fullPath: '/captures/'
      preLoaderRoute: typeof CapturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/$captureId': {
      id: '/captures/$captureId'
      path: '/captures/$captureId'
      fullPath: '/captures/$captureId'
      preLoaderRoute: typeof CapturesCaptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof DocsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calibration': {
      id: '/settings/calibration'
      path: '/calibration'
      fullPath: '/settings/calibration'
      preLoaderRoute: typeof SettingsCalibrationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/map': {
      id: '/settings/map'
      path: '/map'
      fullPath: '/settings/map'
      preLoaderRoute: typeof SettingsMapRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sensors': {
      id: '/settings/sensors'
      path: '/sensors'
      fullPath: '/settings/sensors'
      preLoaderRoute: typeof SettingsSensorsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tracks': {
      id: '/settings/tracks'
      path: '/tracks'
      fullPath: '/settings/tracks'
      preLoaderRoute: typeof SettingsTracksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsDocIdRoute: typeof DocsDocIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocIdRoute: DocsDocIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCalibrationRoute: typeof SettingsCalibrationRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsMapRoute: typeof SettingsMapRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSensorsRoute: typeof SettingsSensorsRoute
  SettingsTracksRoute: typeof SettingsTracksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCalibrationRoute: SettingsCalibrationRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMapRoute: SettingsMapRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSensorsRoute: SettingsSensorsRoute,
  SettingsTracksRoute: SettingsTracksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConfigRoute: ConfigRoute,
  DocsRoute: DocsRouteWithChildren,
  LogsRoute: LogsRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SpectrumRoute: SpectrumRoute,
  TimelineRoute: TimelineRoute,
  CapturesCaptureIdRoute: CapturesCaptureIdRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  CapturesIndexRoute: CapturesIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
