/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CapturesIndexRouteImport } from './routes/captures.index'
import { Route as CapturesCaptureIdRouteImport } from './routes/captures.$captureId'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksTrackIdRouteImport } from './routes/tracks.$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIndexRoute = CapturesIndexRouteImport.update({
  id: '/captures/',
  path: '/captures/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesCaptureIdRoute = CapturesCaptureIdRouteImport.update({
  id: '/captures/$captureId',
  path: '/captures/$captureId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocsRoute,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/docs': typeof DocsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures': typeof CapturesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/docs': typeof DocsRouteWithChildren
  '/logs': typeof LogsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/docs'
    | '/logs'
    | '/sensors'
    | '/settings'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/tracks/$trackId'
    | '/captures/'
    | '/docs/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/logs'
    | '/sensors'
    | '/settings'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/tracks/$trackId'
    | '/captures'
    | '/docs'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/docs'
    | '/logs'
    | '/sensors'
    | '/settings'
    | '/captures/$captureId'
    | '/docs/$docId'
    | '/tracks/$trackId'
    | '/captures/'
    | '/docs/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  DocsRoute: typeof DocsRouteWithChildren
  LogsRoute: typeof LogsRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  CapturesCaptureIdRoute: typeof CapturesCaptureIdRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  CapturesIndexRoute: typeof CapturesIndexRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/': {
      id: '/captures/'
      path: '/captures'
      fullPath: '/captures/'
      preLoaderRoute: typeof CapturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/$captureId': {
      id: '/captures/$captureId'
      path: '/captures/$captureId'
      fullPath: '/captures/$captureId'
      preLoaderRoute: typeof CapturesCaptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof DocsRoute
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsDocIdRoute: typeof DocsDocIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocIdRoute: DocsDocIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  DocsRoute: DocsRouteWithChildren,
  LogsRoute: LogsRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  CapturesCaptureIdRoute: CapturesCaptureIdRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  CapturesIndexRoute: CapturesIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
