/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as CapturesIndexRouteImport } from './routes/captures.index'
import { Route as CapturesCaptureIdRouteImport } from './routes/captures.$captureId'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksTrackIdRouteImport } from './routes/tracks.$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesIndexRoute = CapturesIndexRouteImport.update({
  id: '/captures/',
  path: '/captures/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesCaptureIdRoute = CapturesCaptureIdRouteImport.update({
  id: '/captures/$captureId',
  path: '/captures/$captureId',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/sensors': typeof SensorsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/sensors': typeof SensorsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures': typeof CapturesIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/sensors': typeof SensorsRoute
  '/captures/$captureId': typeof CapturesCaptureIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/captures/': typeof CapturesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/sensors'
    | '/captures/$captureId'
    | '/tracks/$trackId'
    | '/captures/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/sensors'
    | '/captures/$captureId'
    | '/tracks/$trackId'
    | '/captures'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/sensors'
    | '/captures/$captureId'
    | '/tracks/$trackId'
    | '/captures/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  SensorsRoute: typeof SensorsRoute
  CapturesCaptureIdRoute: typeof CapturesCaptureIdRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  CapturesIndexRoute: typeof CapturesIndexRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/': {
      id: '/captures/'
      path: '/captures'
      fullPath: '/captures/'
      preLoaderRoute: typeof CapturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures/$captureId': {
      id: '/captures/$captureId'
      path: '/captures/$captureId'
      fullPath: '/captures/$captureId'
      preLoaderRoute: typeof CapturesCaptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  SensorsRoute: SensorsRoute,
  CapturesCaptureIdRoute: CapturesCaptureIdRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  CapturesIndexRoute: CapturesIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
