// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Capture struct {
	CaptureID string
	Doc       string
	StartedAt string
	Report    sql.NullString
}

type Config struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Detection struct {
	DetectionID    string
	Ts             string
	SensorID       string
	SensorKind     string
	DetectionClass string
	Serial         sql.NullString
	Mac            sql.NullString
	Doc            string
}

type Sensor struct {
	SensorID      string
	SensorKind    string
	LastHeartbeat sql.NullString
	Healthy       int64
	Reason        sql.NullString
	Detail        sql.NullString
}

type Track struct {
	TrackID        string
	State          string
	FirstSeen      string
	LastSeen       string
	DetectionCount int64
	Confidence     float64
	Serial         sql.NullString
	Doc            string
}
