// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Capture struct {
	CaptureID string
	Doc       string
	StartedAt string
	Report    sql.NullString
}

type Config struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Detection struct {
	DetectionID    string
	Ts             string
	SensorID       string
	SensorKind     string
	DetectionClass string
	Serial         sql.NullString
	Mac            sql.NullString
	Doc            string
}

type Sensor struct {
	SensorID      string
	SensorKind    string
	LastHeartbeat sql.NullString
	Healthy       int64
	Reason        sql.NullString
	Detail        sql.NullString
}

type Session struct {
	SessionID string
	UserID    string
	CreatedAt string
	ExpiresAt string
	LastSeen  string
	UserAgent string
	Ip        string
}

type SpectrumSweep struct {
	SweepID   string
	Doc       string
	StartedAt string
	Bins      sql.NullString
}

type Telemetry struct {
	Ts             string
	CpuTempC       sql.NullFloat64
	Load1          sql.NullFloat64
	MemAvailableKb sql.NullInt64
	DiskFreeBytes  sql.NullInt64
	Doc            string
}

type Track struct {
	TrackID        string
	State          string
	FirstSeen      string
	LastSeen       string
	DetectionCount int64
	Confidence     float64
	Serial         sql.NullString
	Doc            string
}

type User struct {
	UserID       string
	Username     string
	DisplayName  string
	Role         string
	PasswordHash sql.NullString
	Issuer       string
	Subject      string
	Disabled     int64
	CreatedAt    string
	UpdatedAt    string
	LastLoginAt  sql.NullString
}
