// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const countDetections = `-- name: CountDetections :one
SELECT COUNT(*) FROM detections
WHERE (CAST(?1 AS TEXT)      IS NULL OR ts        >= ?1)
  AND (CAST(?2 AS TEXT)  IS NULL OR sensor_id  = ?2)
  AND (CAST(?3 AS INTEGER) IS NULL OR detection_class IN (/*SLICE:classes*/?))
`

type CountDetectionsParams struct {
	Since         sql.NullString
	SensorID      sql.NullString
	FilterClasses sql.NullInt64
	Classes       []string
}

func (q *Queries) CountDetections(ctx context.Context, arg CountDetectionsParams) (int64, error) {
	query := countDetections
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Since)
	queryParams = append(queryParams, arg.SensorID)
	queryParams = append(queryParams, arg.FilterClasses)
	if len(arg.Classes) > 0 {
		for _, v := range arg.Classes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:classes*/?", strings.Repeat(",?", len(arg.Classes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:classes*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracks = `-- name: CountTracks :one
SELECT COUNT(*) FROM tracks
WHERE (CAST(?1 AS TEXT)          IS NULL OR last_seen  >= ?1)
  AND (CAST(?2 AS REAL) IS NULL OR confidence >= ?2)
  AND (CAST(?3 AS INTEGER)  IS NULL OR state IN (/*SLICE:states*/?))
`

type CountTracksParams struct {
	Since         sql.NullString
	MinConfidence sql.NullFloat64
	FilterStates  sql.NullInt64
	States        []string
}

func (q *Queries) CountTracks(ctx context.Context, arg CountTracksParams) (int64, error) {
	query := countTracks
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Since)
	queryParams = append(queryParams, arg.MinConfidence)
	queryParams = append(queryParams, arg.FilterStates)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detectionCountsSince = `-- name: DetectionCountsSince :many
SELECT sensor_id, COUNT(*) AS count FROM detections
WHERE ts >= ?
GROUP BY sensor_id
`

type DetectionCountsSinceRow struct {
	SensorID string
	Count    int64
}

// Powers /health's detections_5m, which is how a quiet sky is told apart from
// a broken sensor.
func (q *Queries) DetectionCountsSince(ctx context.Context, ts string) ([]DetectionCountsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, detectionCountsSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectionCountsSinceRow{}
	for rows.Next() {
		var i DetectionCountsSinceRow
		if err := rows.Scan(&i.SensorID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapture = `-- name: GetCapture :one
SELECT doc FROM captures WHERE capture_id = ?
`

func (q *Queries) GetCapture(ctx context.Context, captureID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCapture, captureID)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const getCaptureReport = `-- name: GetCaptureReport :one
SELECT report FROM captures WHERE capture_id = ?
`

func (q *Queries) GetCaptureReport(ctx context.Context, captureID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCaptureReport, captureID)
	var report sql.NullString
	err := row.Scan(&report)
	return report, err
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getTrack = `-- name: GetTrack :one
SELECT doc FROM tracks WHERE track_id = ?
`

func (q *Queries) GetTrack(ctx context.Context, trackID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTrack, trackID)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const insertDetection = `-- name: InsertDetection :exec
INSERT INTO detections (
    detection_id, ts, sensor_id, sensor_kind, detection_class, serial, mac, doc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(detection_id) DO NOTHING
`

type InsertDetectionParams struct {
	DetectionID    string
	Ts             string
	SensorID       string
	SensorKind     string
	DetectionClass string
	Serial         sql.NullString
	Mac            sql.NullString
	Doc            string
}

func (q *Queries) InsertDetection(ctx context.Context, arg InsertDetectionParams) error {
	_, err := q.db.ExecContext(ctx, insertDetection,
		arg.DetectionID,
		arg.Ts,
		arg.SensorID,
		arg.SensorKind,
		arg.DetectionClass,
		arg.Serial,
		arg.Mac,
		arg.Doc,
	)
	return err
}

const listCaptures = `-- name: ListCaptures :many
SELECT doc FROM captures ORDER BY started_at DESC
`

func (q *Queries) ListCaptures(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCaptures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var doc string
		if err := rows.Scan(&doc); err != nil {
			return nil, err
		}
		items = append(items, doc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetections = `-- name: ListDetections :many
SELECT doc, ts, detection_id FROM detections
WHERE (CAST(?2 AS TEXT)      IS NULL OR ts        >= ?2)
  AND (CAST(?3 AS TEXT)  IS NULL OR sensor_id  = ?3)
  AND (CAST(?4 AS INTEGER) IS NULL OR detection_class IN (/*SLICE:classes*/?))
  AND (
        CAST(?6 AS TEXT) IS NULL
        OR ts < ?6
        OR (ts = ?6 AND detection_id < ?7)
      )
ORDER BY ts DESC, detection_id DESC
LIMIT ?
`

type ListDetectionsParams struct {
	Since         sql.NullString
	SensorID      sql.NullString
	FilterClasses sql.NullInt64
	Classes       []string
	CursorTs      sql.NullString
	CursorID      sql.NullString
	Limit         int64
}

type ListDetectionsRow struct {
	Doc         string
	Ts          string
	DetectionID string
}

func (q *Queries) ListDetections(ctx context.Context, arg ListDetectionsParams) ([]ListDetectionsRow, error) {
	query := listDetections
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Since)
	queryParams = append(queryParams, arg.SensorID)
	queryParams = append(queryParams, arg.FilterClasses)
	if len(arg.Classes) > 0 {
		for _, v := range arg.Classes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:classes*/?", strings.Repeat(",?", len(arg.Classes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:classes*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorTs)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetectionsRow{}
	for rows.Next() {
		var i ListDetectionsRow
		if err := rows.Scan(&i.Doc, &i.Ts, &i.DetectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensors = `-- name: ListSensors :many
SELECT sensor_id, sensor_kind, last_heartbeat, healthy, reason, detail
FROM sensors ORDER BY sensor_id
`

func (q *Queries) ListSensors(ctx context.Context) ([]Sensor, error) {
	rows, err := q.db.QueryContext(ctx, listSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sensor{}
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(
			&i.SensorID,
			&i.SensorKind,
			&i.LastHeartbeat,
			&i.Healthy,
			&i.Reason,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT doc, last_seen, track_id FROM tracks
WHERE (CAST(?2 AS TEXT)          IS NULL OR last_seen  >= ?2)
  AND (CAST(?3 AS REAL) IS NULL OR confidence >= ?3)
  AND (CAST(?4 AS INTEGER)  IS NULL OR state IN (/*SLICE:states*/?))
  AND (
        CAST(?6 AS TEXT) IS NULL
        OR last_seen < ?6
        OR (last_seen = ?6 AND track_id < ?7)
      )
ORDER BY last_seen DESC, track_id DESC
LIMIT ?
`

type ListTracksParams struct {
	Since         sql.NullString
	MinConfidence sql.NullFloat64
	FilterStates  sql.NullInt64
	States        []string
	CursorTs      sql.NullString
	CursorID      sql.NullString
	Limit         int64
}

type ListTracksRow struct {
	Doc      string
	LastSeen string
	TrackID  string
}

// Keyset paging on (last_seen DESC, track_id DESC), matching idx_tracks_page.
// Offset paging would silently skip rows on a table being appended to.
func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	query := listTracks
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Since)
	queryParams = append(queryParams, arg.MinConfidence)
	queryParams = append(queryParams, arg.FilterStates)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorTs)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksRow{}
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(&i.Doc, &i.LastSeen, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDetections = `-- name: PurgeDetections :execrows
DELETE FROM detections WHERE ts < ?
`

func (q *Queries) PurgeDetections(ctx context.Context, ts string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeDetections, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeTracks = `-- name: PurgeTracks :execrows
DELETE FROM tracks WHERE last_seen < ?
`

func (q *Queries) PurgeTracks(ctx context.Context, lastSeen string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeTracks, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putCapture = `-- name: PutCapture :exec
INSERT INTO captures (capture_id, doc, started_at) VALUES (?, ?, ?)
ON CONFLICT(capture_id) DO UPDATE SET
    doc        = excluded.doc,
    started_at = excluded.started_at
`

type PutCaptureParams struct {
	CaptureID string
	Doc       string
	StartedAt string
}

func (q *Queries) PutCapture(ctx context.Context, arg PutCaptureParams) error {
	_, err := q.db.ExecContext(ctx, putCapture, arg.CaptureID, arg.Doc, arg.StartedAt)
	return err
}

const putCaptureReport = `-- name: PutCaptureReport :exec
UPDATE captures SET report = ? WHERE capture_id = ?
`

type PutCaptureReportParams struct {
	Report    sql.NullString
	CaptureID string
}

func (q *Queries) PutCaptureReport(ctx context.Context, arg PutCaptureReportParams) error {
	_, err := q.db.ExecContext(ctx, putCaptureReport, arg.Report, arg.CaptureID)
	return err
}

const putConfig = `-- name: PutConfig :exec
INSERT INTO config (key, value, updated_at) VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value      = excluded.value,
    updated_at = excluded.updated_at
`

type PutConfigParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) PutConfig(ctx context.Context, arg PutConfigParams) error {
	_, err := q.db.ExecContext(ctx, putConfig, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}

const upsertSensor = `-- name: UpsertSensor :exec
INSERT INTO sensors (sensor_id, sensor_kind, last_heartbeat, healthy, reason, detail)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(sensor_id) DO UPDATE SET
    sensor_kind    = excluded.sensor_kind,
    last_heartbeat = excluded.last_heartbeat,
    healthy        = excluded.healthy,
    reason         = excluded.reason,
    detail         = excluded.detail
`

type UpsertSensorParams struct {
	SensorID      string
	SensorKind    string
	LastHeartbeat sql.NullString
	Healthy       int64
	Reason        sql.NullString
	Detail        sql.NullString
}

func (q *Queries) UpsertSensor(ctx context.Context, arg UpsertSensorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSensor,
		arg.SensorID,
		arg.SensorKind,
		arg.LastHeartbeat,
		arg.Healthy,
		arg.Reason,
		arg.Detail,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec

INSERT INTO tracks (
    track_id, state, first_seen, last_seen, detection_count, confidence, serial, doc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
    state           = excluded.state,
    first_seen      = excluded.first_seen,
    last_seen       = excluded.last_seen,
    detection_count = excluded.detection_count,
    confidence      = excluded.confidence,
    serial          = excluded.serial,
    doc             = excluded.doc
`

type UpsertTrackParams struct {
	TrackID        string
	State          string
	FirstSeen      string
	LastSeen       string
	DetectionCount int64
	Confidence     float64
	Serial         sql.NullString
	Doc            string
}

// Every statement the store runs. sqlc type-checks each one against
// schema.sql and generates the Go, so a column that no longer exists is a
// build failure rather than a runtime error on a detector that is mid-flight.
//
// The list queries previously concatenated WHERE clauses in Go. They are now
// single statements with NULL-guarded optional filters: `sqlc.narg('x') IS NULL
// OR col = sqlc.narg('x')`. That trades a little index selectivity for queries
// that can be verified at build time and have no string-building to get wrong.
// At a Pi's data volumes -- weeks of detections, not billions -- the trade is
// firmly worth it.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.TrackID,
		arg.State,
		arg.FirstSeen,
		arg.LastSeen,
		arg.DetectionCount,
		arg.Confidence,
		arg.Serial,
		arg.Doc,
	)
	return err
}
