// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Guards the last admin. Deleting or demoting the only one leaves a box nobody
	// can administer, recoverable only by editing the database by hand.
	CountAdmins(ctx context.Context) (int64, error)
	CountDetections(ctx context.Context, arg CountDetectionsParams) (int64, error)
	// Reconstructing one track's detections matches on serial OR MAC, because a
	// track is keyed by MAC until Basic ID arrives and by serial afterwards, and
	// the same flight has rows from both eras.
	//
	// Note the shape: each side of the OR is guarded by its own NOT NULL check, so
	// a track with only a MAC does not accidentally match every row whose serial is
	// NULL -- which, early in a flight, is most of them. The caller returns early
	// when a track has neither.
	CountTrackDetections(ctx context.Context, arg CountTrackDetectionsParams) (int64, error)
	CountTracks(ctx context.Context, arg CountTracksParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	DeleteSession(ctx context.Context, sessionID string) (int64, error)
	DeleteUser(ctx context.Context, userID string) (int64, error)
	DeleteUserSessions(ctx context.Context, userID string) (int64, error)
	// Powers /health's detections_5m, which is how a quiet sky is told apart from
	// a broken sensor.
	DetectionCountsSince(ctx context.Context, ts string) ([]DetectionCountsSinceRow, error)
	GetCapture(ctx context.Context, captureID string) (string, error)
	GetCaptureReport(ctx context.Context, captureID string) (sql.NullString, error)
	GetConfig(ctx context.Context, key string) (string, error)
	GetSession(ctx context.Context, sessionID string) (Session, error)
	GetSweep(ctx context.Context, sweepID string) (string, error)
	GetSweepBins(ctx context.Context, sweepID string) (sql.NullString, error)
	GetTrack(ctx context.Context, trackID string) (string, error)
	GetUser(ctx context.Context, userID string) (User, error)
	// `issuer <> ''` is load-bearing, not tidiness. Local accounts store ('',''),
	// so without it a lookup with an empty issuer matches the first local account
	// it finds -- and an SSO login would come back as an existing operator. The
	// memstore refuses an empty issuer explicitly; this is the SQL half of the same
	// rule, and storetest checks both.
	GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertDetection(ctx context.Context, arg InsertDetectionParams) error
	// Ignores a duplicate timestamp rather than failing: two samplers, or a restart
	// inside one sampling interval, must not take the api down.
	InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) error
	ListCaptures(ctx context.Context) ([]string, error)
	ListDetections(ctx context.Context, arg ListDetectionsParams) ([]ListDetectionsRow, error)
	ListSensors(ctx context.Context) ([]Sensor, error)
	ListSessions(ctx context.Context, limit int64) ([]Session, error)
	// Newest first, and deliberately without `bins`: the list is a menu, and
	// dragging every measurement off disk to render it would make the page cost
	// megabytes to answer "which sweeps do I have".
	ListSweeps(ctx context.Context, limit int64) ([]string, error)
	// Ascending, because every consumer is a chart and a chart reads left to right.
	ListTelemetry(ctx context.Context, arg ListTelemetryParams) ([]Telemetry, error)
	ListTrackDetections(ctx context.Context, arg ListTrackDetectionsParams) ([]ListTrackDetectionsRow, error)
	// Keyset paging on (last_seen DESC, track_id DESC), matching idx_tracks_page.
	// Offset paging would silently skip rows on a table being appended to.
	ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	PurgeDetections(ctx context.Context, ts string) (int64, error)
	PurgeExpiredSessions(ctx context.Context, expiresAt string) (int64, error)
	PurgeSweeps(ctx context.Context, startedAt string) (int64, error)
	PurgeTelemetry(ctx context.Context, ts string) (int64, error)
	PurgeTracks(ctx context.Context, lastSeen string) (int64, error)
	PutCapture(ctx context.Context, arg PutCaptureParams) error
	// doc is rewritten alongside the report because the analysis summary lives in
	// the capture document too; writing only one of the pair would leave a capture
	// whose summary and report disagree. :execrows so a missing capture_id is
	// reported as not-found rather than passing silently.
	PutCaptureReport(ctx context.Context, arg PutCaptureReportParams) (int64, error)
	PutConfig(ctx context.Context, arg PutConfigParams) error
	PutSession(ctx context.Context, arg PutSessionParams) error
	PutSweep(ctx context.Context, arg PutSweepParams) error
	// Separate from PutSweep so finishing a sweep does not rewrite the megabyte,
	// and so a failed sweep stores its reason without storing an empty blob.
	PutSweepBins(ctx context.Context, arg PutSweepBinsParams) error
	PutUser(ctx context.Context, arg PutUserParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpsertSensor(ctx context.Context, arg UpsertSensorParams) error
	// Every statement the store runs. sqlc type-checks each one against
	// schema.sql and generates the Go, so a column that no longer exists is a
	// build failure rather than a runtime error on a detector that is mid-flight.
	//
	// The list queries previously concatenated WHERE clauses in Go. They are now
	// single statements with NULL-guarded optional filters: `sqlc.narg('x') IS NULL
	// OR col = sqlc.narg('x')`. That trades a little index selectivity for queries
	// that can be verified at build time and have no string-building to get wrong.
	// At a Pi's data volumes -- weeks of detections, not billions -- the trade is
	// firmly worth it.
	//
	// Set filters ("state IN (...)") pass a JSON array as ONE parameter and expand
	// it with json_each, rather than using sqlc.slice(). That is not a style
	// preference. sqlc numbers parameters explicitly (?1, ?2, ...) as soon as a
	// query uses named parameters, but sqlc.slice() expands to bare `?`, which
	// SQLite numbers as "one past the highest so far". The two schemes only agree
	// when the slice happens to hold exactly one element; at zero or two the
	// parameters after it silently shift and a confidence float ends up compared
	// against a timestamp. A JSON array is a single parameter of fixed position, so
	// the numbering cannot drift, and NULL still means "no filter".
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) error
}

var _ Querier = (*Queries)(nil)
