// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countDetections = `-- name: CountDetections :one
SELECT COUNT(*) FROM detections
WHERE (CAST(?1 AS TEXT)     IS NULL OR ts        >= ?1)
  AND (CAST(?2 AS TEXT) IS NULL OR sensor_id  = ?2)
  AND (CAST(?3 AS TEXT)   IS NULL
       OR detection_class IN (SELECT value FROM json_each(?3)))
`

type CountDetectionsParams struct {
	Since    sql.NullString
	SensorID sql.NullString
	Classes  sql.NullString
}

func (q *Queries) CountDetections(ctx context.Context, arg CountDetectionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDetections, arg.Since, arg.SensorID, arg.Classes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrackDetections = `-- name: CountTrackDetections :one

SELECT COUNT(*) FROM detections
WHERE (
        (CAST(?1 AS TEXT) IS NOT NULL AND serial = ?1)
     OR (CAST(?2 AS TEXT) IS NOT NULL
         AND mac IN (SELECT value FROM json_each(?2)))
      )
  AND (CAST(?3 AS TEXT) IS NULL OR ts >= ?3)
  AND (CAST(?4   AS TEXT) IS NULL OR ts <= ?4)
`

type CountTrackDetectionsParams struct {
	Serial sql.NullString
	Macs   sql.NullString
	FromTs sql.NullString
	ToTs   sql.NullString
}

// Reconstructing one track's detections matches on serial OR MAC, because a
// track is keyed by MAC until Basic ID arrives and by serial afterwards, and
// the same flight has rows from both eras.
//
// Note the shape: each side of the OR is guarded by its own NOT NULL check, so
// a track with only a MAC does not accidentally match every row whose serial is
// NULL -- which, early in a flight, is most of them. The caller returns early
// when a track has neither.
func (q *Queries) CountTrackDetections(ctx context.Context, arg CountTrackDetectionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrackDetections,
		arg.Serial,
		arg.Macs,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracks = `-- name: CountTracks :one
SELECT COUNT(*) FROM tracks
WHERE (CAST(?1 AS TEXT)          IS NULL OR last_seen  >= ?1)
  AND (CAST(?2 AS REAL) IS NULL OR confidence >= ?2)
  AND (CAST(?3 AS TEXT)         IS NULL
       OR state IN (SELECT value FROM json_each(?3)))
`

type CountTracksParams struct {
	Since         sql.NullString
	MinConfidence sql.NullFloat64
	States        sql.NullString
}

func (q *Queries) CountTracks(ctx context.Context, arg CountTracksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTracks, arg.Since, arg.MinConfidence, arg.States)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detectionCountsSince = `-- name: DetectionCountsSince :many
SELECT sensor_id, COUNT(*) AS count FROM detections
WHERE ts >= ?
GROUP BY sensor_id
`

type DetectionCountsSinceRow struct {
	SensorID string
	Count    int64
}

// Powers /health's detections_5m, which is how a quiet sky is told apart from
// a broken sensor.
func (q *Queries) DetectionCountsSince(ctx context.Context, ts string) ([]DetectionCountsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, detectionCountsSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectionCountsSinceRow{}
	for rows.Next() {
		var i DetectionCountsSinceRow
		if err := rows.Scan(&i.SensorID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapture = `-- name: GetCapture :one
SELECT doc FROM captures WHERE capture_id = ?
`

func (q *Queries) GetCapture(ctx context.Context, captureID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCapture, captureID)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const getCaptureReport = `-- name: GetCaptureReport :one
SELECT report FROM captures WHERE capture_id = ?
`

func (q *Queries) GetCaptureReport(ctx context.Context, captureID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCaptureReport, captureID)
	var report sql.NullString
	err := row.Scan(&report)
	return report, err
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSweep = `-- name: GetSweep :one
SELECT doc FROM spectrum_sweeps WHERE sweep_id = ?
`

func (q *Queries) GetSweep(ctx context.Context, sweepID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSweep, sweepID)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const getSweepBins = `-- name: GetSweepBins :one
SELECT bins FROM spectrum_sweeps WHERE sweep_id = ?
`

func (q *Queries) GetSweepBins(ctx context.Context, sweepID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSweepBins, sweepID)
	var bins sql.NullString
	err := row.Scan(&bins)
	return bins, err
}

const getTrack = `-- name: GetTrack :one
SELECT doc FROM tracks WHERE track_id = ?
`

func (q *Queries) GetTrack(ctx context.Context, trackID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTrack, trackID)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const insertDetection = `-- name: InsertDetection :exec
INSERT INTO detections (
    detection_id, ts, sensor_id, sensor_kind, detection_class, serial, mac, doc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(detection_id) DO NOTHING
`

type InsertDetectionParams struct {
	DetectionID    string
	Ts             string
	SensorID       string
	SensorKind     string
	DetectionClass string
	Serial         sql.NullString
	Mac            sql.NullString
	Doc            string
}

func (q *Queries) InsertDetection(ctx context.Context, arg InsertDetectionParams) error {
	_, err := q.db.ExecContext(ctx, insertDetection,
		arg.DetectionID,
		arg.Ts,
		arg.SensorID,
		arg.SensorKind,
		arg.DetectionClass,
		arg.Serial,
		arg.Mac,
		arg.Doc,
	)
	return err
}

const insertTelemetry = `-- name: InsertTelemetry :exec
INSERT INTO telemetry (ts, cpu_temp_c, load1, mem_available_kb, disk_free_bytes, doc)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(ts) DO NOTHING
`

type InsertTelemetryParams struct {
	Ts             string
	CpuTempC       sql.NullFloat64
	Load1          sql.NullFloat64
	MemAvailableKb sql.NullInt64
	DiskFreeBytes  sql.NullInt64
	Doc            string
}

// Ignores a duplicate timestamp rather than failing: two samplers, or a restart
// inside one sampling interval, must not take the api down.
func (q *Queries) InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetry,
		arg.Ts,
		arg.CpuTempC,
		arg.Load1,
		arg.MemAvailableKb,
		arg.DiskFreeBytes,
		arg.Doc,
	)
	return err
}

const listCaptures = `-- name: ListCaptures :many
SELECT doc FROM captures ORDER BY started_at DESC
`

func (q *Queries) ListCaptures(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCaptures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var doc string
		if err := rows.Scan(&doc); err != nil {
			return nil, err
		}
		items = append(items, doc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetections = `-- name: ListDetections :many
SELECT doc, ts, detection_id FROM detections
WHERE (CAST(?1 AS TEXT)     IS NULL OR ts        >= ?1)
  AND (CAST(?2 AS TEXT) IS NULL OR sensor_id  = ?2)
  AND (CAST(?3 AS TEXT)   IS NULL
       OR detection_class IN (SELECT value FROM json_each(?3)))
  AND (
        CAST(?4 AS TEXT) IS NULL
        OR ts < ?4
        OR (ts = ?4 AND detection_id < ?5)
      )
ORDER BY ts DESC, detection_id DESC
LIMIT ?6
`

type ListDetectionsParams struct {
	Since    sql.NullString
	SensorID sql.NullString
	Classes  sql.NullString
	CursorTs sql.NullString
	CursorID sql.NullString
	Limit    int64
}

type ListDetectionsRow struct {
	Doc         string
	Ts          string
	DetectionID string
}

func (q *Queries) ListDetections(ctx context.Context, arg ListDetectionsParams) ([]ListDetectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetections,
		arg.Since,
		arg.SensorID,
		arg.Classes,
		arg.CursorTs,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetectionsRow{}
	for rows.Next() {
		var i ListDetectionsRow
		if err := rows.Scan(&i.Doc, &i.Ts, &i.DetectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensors = `-- name: ListSensors :many
SELECT sensor_id, sensor_kind, last_heartbeat, healthy, reason, detail
FROM sensors ORDER BY sensor_id
`

func (q *Queries) ListSensors(ctx context.Context) ([]Sensor, error) {
	rows, err := q.db.QueryContext(ctx, listSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sensor{}
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(
			&i.SensorID,
			&i.SensorKind,
			&i.LastHeartbeat,
			&i.Healthy,
			&i.Reason,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweeps = `-- name: ListSweeps :many
SELECT doc FROM spectrum_sweeps ORDER BY started_at DESC LIMIT ?
`

// Newest first, and deliberately without `bins`: the list is a menu, and
// dragging every measurement off disk to render it would make the page cost
// megabytes to answer "which sweeps do I have".
func (q *Queries) ListSweeps(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSweeps, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var doc string
		if err := rows.Scan(&doc); err != nil {
			return nil, err
		}
		items = append(items, doc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetry = `-- name: ListTelemetry :many
SELECT ts, cpu_temp_c, load1, mem_available_kb, disk_free_bytes, doc
FROM telemetry
WHERE ts >= ? AND ts <= ?
ORDER BY ts ASC
LIMIT ?
`

type ListTelemetryParams struct {
	Ts    string
	Ts_2  string
	Limit int64
}

// Ascending, because every consumer is a chart and a chart reads left to right.
func (q *Queries) ListTelemetry(ctx context.Context, arg ListTelemetryParams) ([]Telemetry, error) {
	rows, err := q.db.QueryContext(ctx, listTelemetry, arg.Ts, arg.Ts_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Telemetry{}
	for rows.Next() {
		var i Telemetry
		if err := rows.Scan(
			&i.Ts,
			&i.CpuTempC,
			&i.Load1,
			&i.MemAvailableKb,
			&i.DiskFreeBytes,
			&i.Doc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackDetections = `-- name: ListTrackDetections :many
SELECT doc, ts, detection_id FROM detections
WHERE (
        (CAST(?1 AS TEXT) IS NOT NULL AND serial = ?1)
     OR (CAST(?2 AS TEXT) IS NOT NULL
         AND mac IN (SELECT value FROM json_each(?2)))
      )
  AND (CAST(?3 AS TEXT) IS NULL OR ts >= ?3)
  AND (CAST(?4   AS TEXT) IS NULL OR ts <= ?4)
  AND (
        CAST(?5 AS TEXT) IS NULL
        OR ts < ?5
        OR (ts = ?5 AND detection_id < ?6)
      )
ORDER BY ts DESC, detection_id DESC
LIMIT ?7
`

type ListTrackDetectionsParams struct {
	Serial   sql.NullString
	Macs     sql.NullString
	FromTs   sql.NullString
	ToTs     sql.NullString
	CursorTs sql.NullString
	CursorID sql.NullString
	Limit    int64
}

type ListTrackDetectionsRow struct {
	Doc         string
	Ts          string
	DetectionID string
}

func (q *Queries) ListTrackDetections(ctx context.Context, arg ListTrackDetectionsParams) ([]ListTrackDetectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackDetections,
		arg.Serial,
		arg.Macs,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackDetectionsRow{}
	for rows.Next() {
		var i ListTrackDetectionsRow
		if err := rows.Scan(&i.Doc, &i.Ts, &i.DetectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT doc, last_seen, track_id FROM tracks
WHERE (CAST(?1 AS TEXT)          IS NULL OR last_seen  >= ?1)
  AND (CAST(?2 AS REAL) IS NULL OR confidence >= ?2)
  AND (CAST(?3 AS TEXT)         IS NULL
       OR state IN (SELECT value FROM json_each(?3)))
  AND (
        CAST(?4 AS TEXT) IS NULL
        OR last_seen < ?4
        OR (last_seen = ?4 AND track_id < ?5)
      )
ORDER BY last_seen DESC, track_id DESC
LIMIT ?6
`

type ListTracksParams struct {
	Since         sql.NullString
	MinConfidence sql.NullFloat64
	States        sql.NullString
	CursorTs      sql.NullString
	CursorID      sql.NullString
	Limit         int64
}

type ListTracksRow struct {
	Doc      string
	LastSeen string
	TrackID  string
}

// Keyset paging on (last_seen DESC, track_id DESC), matching idx_tracks_page.
// Offset paging would silently skip rows on a table being appended to.
func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracks,
		arg.Since,
		arg.MinConfidence,
		arg.States,
		arg.CursorTs,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksRow{}
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(&i.Doc, &i.LastSeen, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDetections = `-- name: PurgeDetections :execrows
DELETE FROM detections WHERE ts < ?
`

func (q *Queries) PurgeDetections(ctx context.Context, ts string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeDetections, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeSweeps = `-- name: PurgeSweeps :execrows
DELETE FROM spectrum_sweeps WHERE started_at < ?
`

func (q *Queries) PurgeSweeps(ctx context.Context, startedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSweeps, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeTelemetry = `-- name: PurgeTelemetry :execrows
DELETE FROM telemetry WHERE ts < ?
`

func (q *Queries) PurgeTelemetry(ctx context.Context, ts string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeTelemetry, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeTracks = `-- name: PurgeTracks :execrows
DELETE FROM tracks WHERE last_seen < ?
`

func (q *Queries) PurgeTracks(ctx context.Context, lastSeen string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeTracks, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putCapture = `-- name: PutCapture :exec
INSERT INTO captures (capture_id, doc, started_at) VALUES (?, ?, ?)
ON CONFLICT(capture_id) DO UPDATE SET
    doc        = excluded.doc,
    started_at = excluded.started_at
`

type PutCaptureParams struct {
	CaptureID string
	Doc       string
	StartedAt string
}

func (q *Queries) PutCapture(ctx context.Context, arg PutCaptureParams) error {
	_, err := q.db.ExecContext(ctx, putCapture, arg.CaptureID, arg.Doc, arg.StartedAt)
	return err
}

const putCaptureReport = `-- name: PutCaptureReport :execrows
UPDATE captures SET doc = ?, report = ? WHERE capture_id = ?
`

type PutCaptureReportParams struct {
	Doc       string
	Report    sql.NullString
	CaptureID string
}

// doc is rewritten alongside the report because the analysis summary lives in
// the capture document too; writing only one of the pair would leave a capture
// whose summary and report disagree. :execrows so a missing capture_id is
// reported as not-found rather than passing silently.
func (q *Queries) PutCaptureReport(ctx context.Context, arg PutCaptureReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putCaptureReport, arg.Doc, arg.Report, arg.CaptureID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putConfig = `-- name: PutConfig :exec
INSERT INTO config (key, value, updated_at) VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value      = excluded.value,
    updated_at = excluded.updated_at
`

type PutConfigParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) PutConfig(ctx context.Context, arg PutConfigParams) error {
	_, err := q.db.ExecContext(ctx, putConfig, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}

const putSweep = `-- name: PutSweep :exec
INSERT INTO spectrum_sweeps (sweep_id, doc, started_at)
VALUES (?, ?, ?)
ON CONFLICT(sweep_id) DO UPDATE SET doc = excluded.doc
`

type PutSweepParams struct {
	SweepID   string
	Doc       string
	StartedAt string
}

func (q *Queries) PutSweep(ctx context.Context, arg PutSweepParams) error {
	_, err := q.db.ExecContext(ctx, putSweep, arg.SweepID, arg.Doc, arg.StartedAt)
	return err
}

const putSweepBins = `-- name: PutSweepBins :exec
UPDATE spectrum_sweeps SET bins = ? WHERE sweep_id = ?
`

type PutSweepBinsParams struct {
	Bins    sql.NullString
	SweepID string
}

// Separate from PutSweep so finishing a sweep does not rewrite the megabyte,
// and so a failed sweep stores its reason without storing an empty blob.
func (q *Queries) PutSweepBins(ctx context.Context, arg PutSweepBinsParams) error {
	_, err := q.db.ExecContext(ctx, putSweepBins, arg.Bins, arg.SweepID)
	return err
}

const upsertSensor = `-- name: UpsertSensor :exec
INSERT INTO sensors (sensor_id, sensor_kind, last_heartbeat, healthy, reason, detail)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(sensor_id) DO UPDATE SET
    sensor_kind    = excluded.sensor_kind,
    last_heartbeat = excluded.last_heartbeat,
    healthy        = excluded.healthy,
    reason         = excluded.reason,
    detail         = excluded.detail
`

type UpsertSensorParams struct {
	SensorID      string
	SensorKind    string
	LastHeartbeat sql.NullString
	Healthy       int64
	Reason        sql.NullString
	Detail        sql.NullString
}

func (q *Queries) UpsertSensor(ctx context.Context, arg UpsertSensorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSensor,
		arg.SensorID,
		arg.SensorKind,
		arg.LastHeartbeat,
		arg.Healthy,
		arg.Reason,
		arg.Detail,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec

INSERT INTO tracks (
    track_id, state, first_seen, last_seen, detection_count, confidence, serial, doc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
    state           = excluded.state,
    first_seen      = excluded.first_seen,
    last_seen       = excluded.last_seen,
    detection_count = excluded.detection_count,
    confidence      = excluded.confidence,
    serial          = excluded.serial,
    doc             = excluded.doc
`

type UpsertTrackParams struct {
	TrackID        string
	State          string
	FirstSeen      string
	LastSeen       string
	DetectionCount int64
	Confidence     float64
	Serial         sql.NullString
	Doc            string
}

// Every statement the store runs. sqlc type-checks each one against
// schema.sql and generates the Go, so a column that no longer exists is a
// build failure rather than a runtime error on a detector that is mid-flight.
//
// The list queries previously concatenated WHERE clauses in Go. They are now
// single statements with NULL-guarded optional filters: `sqlc.narg('x') IS NULL
// OR col = sqlc.narg('x')`. That trades a little index selectivity for queries
// that can be verified at build time and have no string-building to get wrong.
// At a Pi's data volumes -- weeks of detections, not billions -- the trade is
// firmly worth it.
//
// Set filters ("state IN (...)") pass a JSON array as ONE parameter and expand
// it with json_each, rather than using sqlc.slice(). That is not a style
// preference. sqlc numbers parameters explicitly (?1, ?2, ...) as soon as a
// query uses named parameters, but sqlc.slice() expands to bare `?`, which
// SQLite numbers as "one past the highest so far". The two schemes only agree
// when the slice happens to hold exactly one element; at zero or two the
// parameters after it silently shift and a confidence float ends up compared
// against a timestamp. A JSON array is a single parameter of fixed position, so
// the numbering cannot drift, and NULL still means "no filter".
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.TrackID,
		arg.State,
		arg.FirstSeen,
		arg.LastSeen,
		arg.DetectionCount,
		arg.Confidence,
		arg.Serial,
		arg.Doc,
	)
	return err
}
