// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountDetections(ctx context.Context, arg CountDetectionsParams) (int64, error)
	CountTracks(ctx context.Context, arg CountTracksParams) (int64, error)
	// Powers /health's detections_5m, which is how a quiet sky is told apart from
	// a broken sensor.
	DetectionCountsSince(ctx context.Context, ts string) ([]DetectionCountsSinceRow, error)
	GetCapture(ctx context.Context, captureID string) (string, error)
	GetCaptureReport(ctx context.Context, captureID string) (sql.NullString, error)
	GetConfig(ctx context.Context, key string) (string, error)
	GetTrack(ctx context.Context, trackID string) (string, error)
	InsertDetection(ctx context.Context, arg InsertDetectionParams) error
	ListCaptures(ctx context.Context) ([]string, error)
	ListDetections(ctx context.Context, arg ListDetectionsParams) ([]ListDetectionsRow, error)
	ListSensors(ctx context.Context) ([]Sensor, error)
	// Keyset paging on (last_seen DESC, track_id DESC), matching idx_tracks_page.
	// Offset paging would silently skip rows on a table being appended to.
	ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error)
	PurgeDetections(ctx context.Context, ts string) (int64, error)
	PurgeTracks(ctx context.Context, lastSeen string) (int64, error)
	PutCapture(ctx context.Context, arg PutCaptureParams) error
	PutCaptureReport(ctx context.Context, arg PutCaptureReportParams) error
	PutConfig(ctx context.Context, arg PutConfigParams) error
	UpsertSensor(ctx context.Context, arg UpsertSensorParams) error
	// Every statement the store runs. sqlc type-checks each one against
	// schema.sql and generates the Go, so a column that no longer exists is a
	// build failure rather than a runtime error on a detector that is mid-flight.
	//
	// The list queries previously concatenated WHERE clauses in Go. They are now
	// single statements with NULL-guarded optional filters: `sqlc.narg('x') IS NULL
	// OR col = sqlc.narg('x')`. That trades a little index selectivity for queries
	// that can be verified at build time and have no string-building to get wrong.
	// At a Pi's data volumes -- weeks of detections, not billions -- the trade is
	// firmly worth it.
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) error
}

var _ Querier = (*Queries)(nil)
